-- Run this script in your Supabase SQL Editor to create the table

create table students (
  id bigint generated by default as identity primary key,
  student_id text unique not null,
  first_name text not null,
  last_name text not null,
  course text not null,
  year_level int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Enable Row Level Security (RLS)
-- alter table students enable row level security;

-- Policy to allow anonymous read/write (since we are using anon key for simple demo)
-- create policy "Enable all access for all users" on students for all using (true) with check (true);
